import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/i01">I01</Link>
        </li>
        <li>
          <Link to="/i02">I02</Link>
        </li>
        <li>
          <Link to="/i03">I03</Link>
        </li>
        <li>
          <Link to="/i04">I04</Link>
        </li>
        <li>
          <Link to="/i05">I05</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
